import os
from pydantic import BaseModel, Field
from harnessfoam.agents.llm_config import build_llm, create_structured_chain
from langchain_core.prompts import PromptTemplate
from dotenv import load_dotenv
import logging
logger = logging.getLogger(__name__)


load_dotenv()

class SlurmScriptResult(BaseModel):
    script_content: str = Field(description="The complete Slurm submission script content")

def build_runner_agent(llm_kwargs: dict = None):
    kwargs = (llm_kwargs or {}).copy()
    if 'temperature' not in kwargs: kwargs['temperature'] = 0.1
    llm = build_llm(**kwargs)
    
    prompt = PromptTemplate(
        template="""You are an expert in OpenFOAM and HPC clusters.
Generate a Slurm script based on the provided user requirement. 

User requirement: {user_requirement}

Output ONLY the script content. Ensure that the script is fully functional and matches the specific cluster requirements (e.g., Perlmutter) if mentioned.
""",
        input_variables=["user_requirement"]
    )
    
    chain = create_structured_chain(llm, prompt, SlurmScriptResult)
    return chain

def generate_hpc_script(prompt_text: str, llm_kwargs: dict = None, memory_context: str = "") -> str:
    """Execute the runner agent to generate a slurm script if HPC is requested."""
    # 2026-08-15 – Gemini 3.5 Flash: return a placeholder, handled locally by the graph or server
    if "hpc" not in prompt_text.lower() and "slurm" not in prompt_text.lower() and "cluster" not in prompt_text.lower():
        return "# Local run, no Slurm script needed.\n# Done."
        
    try:
        chain = build_runner_agent(llm_kwargs=llm_kwargs)
        result = chain.invoke({"user_requirement": prompt_text + memory_context})
        return result.script_content
    except Exception as e:
        logger.info(f"Runner Agent failed: {e}")
        # Fallback script
        return "#!/bin/bash\n#SBATCH -N 1\n#SBATCH -n 32\n./Allrun -parallel"

import subprocess
import os
import shutil
import re
import asyncio

def generate_local_script(case_dir: str) -> str:
    """Determine solver from controlDict and generate local Allrun script."""
    solver_name = "icoFoam"
    control_dict_path = os.path.join(case_dir, "system", "controlDict")
    if os.path.exists(control_dict_path):
        try:
            with open(control_dict_path, "r", encoding="utf-8") as f:
                content = f.read()
            match = re.search(r"application\s+(\w+);", content)
            if match:
                solver_name = match.group(1)
        except Exception:
            pass
            
    local_script = f"""#!/bin/bash
set -e
# Local execution script generated by HarnessFOAM

# Source OpenFOAM environment in WSL/Linux if not already set
if [ -z "$WM_PROJECT_DIR" ]; then
    for foamrc in /opt/openfoam13/etc/bashrc /opt/openfoam*/etc/bashrc; do
        if [ -f "$foamrc" ]; then . "$foamrc" 2>/dev/null || true; break; fi
    done
fi

# Run mesh generation
if [ -f mesh.py ]; then
    echo "Running custom Gmsh python script..."
    python3 mesh.py
    echo "Importing gmsh mesh..."
    gmshToFoam mesh.msh
else
    echo "Running native blockMesh..."
    blockMesh
fi

echo "Checking mesh quality..."
checkMesh

# Run solver
echo "Running solver {solver_name}..."
{solver_name}
echo "Simulation complete!"
"""
    return local_script

def execute_local_simulation(case_dir: str, websocket=None, loop=None) -> tuple[int, str, str]:
    """Execute the local Allrun script in the case directory, streaming to websocket."""
    # Determine the correct shell executor based on OS
    if shutil.which("wsl"):
        abs_case_dir = os.path.abspath(case_dir)
        if len(abs_case_dir) >= 2 and abs_case_dir[1] == ':':
            wsl_case_dir = "/mnt/" + abs_case_dir[0].lower() + abs_case_dir[2:].replace('\\', '/')
        else:
            wsl_case_dir = abs_case_dir
        cmd = ["wsl", "bash", "-lc", f"cd '{wsl_case_dir}' && bash ./Allrun"]
    elif shutil.which("bash"):
        cmd = ["bash", "./Allrun"]
    else:
        cmd = ["sh", "./Allrun"]

    process = subprocess.Popen(
        cmd,
        cwd=case_dir,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1
    )
    
    run_output = []
    for line in process.stdout:
        line_clean = line.rstrip()
        run_output.append(line_clean)
        logger.info(f"[OpenFOAM] {line_clean}")
        if websocket and loop:
            try:
                asyncio.run_coroutine_threadsafe(
                    websocket.send_json({
                        "type": "openfoam_log",
                        "message": line_clean,
                        "is_error": False
                    }),
                    loop
                )
            except Exception:
                pass
                
    process.wait(timeout=300)
    stdout_str = "\n".join(run_output)
    return process.returncode, stdout_str, ""
