from harnessfoam.agents.llm_config import DeepSeekRobustParser
from harnessfoam.agents.visualizer import VisualizationScriptResult

parser = DeepSeekRobustParser(pydantic_object=VisualizationScriptResult)

# Test string that might be generated by the LLM
test_str = """{"properties": {"is_visualization_required": {"description": "True if the user requested any visualization, False otherwise.", "title": "Is Visualization Required", "type": "boolean"}, "pyvista_script": {"description": "The complete python script using pyvista to render the flow field and save as .png. Empty if not required.", "title": "Pyvista Script", "type": "string"}}, "required": ["is_visualization_required", "pyvista_script"], "title": "VisualizationScriptResult", "type": "object"} } {"is_visualization_required": true, "pyvista_script": "import pyvista as pv\\nimport numpy as np\\n\\n# Create empty case.foam file\\nwith open(\\"case.foam\\", \\"w\\") as f:\\n pass\\n\\n# Read OpenFOAM case\\nreader = pv.OpenFOAMReader(\\"case.foam\\")\\nreader.set_active_time_value(reader.time_values[-1])\\nmesh = reader.read()\\n\\n# Get the internal mesh block\\ninternal_mesh = mesh[0]\\n\\n# Compute velocity magnitude from U vector components\\nU = internal_mesh['U']\\nU_magnitude = np.linalg.norm(U, axis=1)\\ninternal_mesh['U_magnitude'] = U_magnitude\\n\\n# Create plotter and visualize velocity magnitude\\nplotter = pv.Plotter(off_screen=True)\\nplotter.add_mesh(internal_mesh, scalars='U_magnitude', cmap='jet', show_edges=False)\\nplotter.add_scalar_bar(title='Velocity Magnitude (m/s)')\\nplotter.view_isometric)\\nplotter.screenshot('visualization.png')\\nplotter.close()\\n"}"""

try:
    res = parser.parse(test_str)
    print("SUCCESS!", res)
except Exception as e:
    print("FAILED:", e)
